# Generated by Django 4.2.2 on 2024-09-16 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('comment', models.TextField(blank=True, default='', verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='тема письма')),
                ('content', models.TextField(verbose_name='письмо')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='дата старта')),
                ('period', models.CharField(choices=[('C', 'кастомный'), ('D', 'каждый день'), ('W', 'каждую неделю'), ('M', 'каждый месяц')], max_length=1, verbose_name='период рассылки')),
                ('status', models.CharField(choices=[('C', 'создана'), ('R', 'запущена'), ('F', 'остановлена')], default='C', max_length=1, verbose_name='статус рассылки')),
                ('clients', models.ManyToManyField(to='mail.client')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='mail.message', verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('status', models.SmallIntegerField(choices=[(1, 'Удачно'), (0, 'Провал')], verbose_name='статус')),
                ('server_response', models.TextField(blank=True, default='', verbose_name='ответ от сервера')),
                ('mailings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mail.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
            },
        ),
    ]
