# Generated by Django 4.2.2 on 2024-09-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
    ]
